import { MonthlyAttendanceRecord, AttendanceRecord, AttendanceStatus, ActionLog } from '../types';

/**
 * SALERY ATTENDANCE GRID SERVICE
 * ─────────────────────────────────────────────────────────────────
 * Handles persistence for the Monthly Grid and bridging to the 
 * core Attendance system for Payroll calculations.
 */

/**
 * Saves the monthly grid raw data to localStorage (Mocking DB)
 */
export const saveMonthlyGrid = async (records: MonthlyAttendanceRecord[]): Promise<void> => {
    console.log(`[GRID SERVICE] Saving ${records.length} grid records...`);

    // Simulate DB Delay
    await new Promise(resolve => setTimeout(resolve, 800));

    const existingRaw = localStorage.getItem('salaire_monthly_grid');
    const existing: MonthlyAttendanceRecord[] = existingRaw ? JSON.parse(existingRaw) : [];

    // Merge logic: replace existing records for same emp/year/month/day
    const recordMap = new Map(existing.map(r => [`${r.employeeId}-${r.year}-${r.month}-${r.day}`, r]));

    records.forEach(r => {
        recordMap.set(`${r.employeeId}-${r.year}-${r.month}-${r.day}`, r);
    });

    localStorage.setItem('salaire_monthly_grid', JSON.stringify(Array.from(recordMap.values())));
};

/**
 * Loads the monthly grid raw data
 */
export const getMonthlyGrid = async (year: number, month: number): Promise<MonthlyAttendanceRecord[]> => {
    const raw = localStorage.getItem('salaire_monthly_grid');
    if (!raw) return [];

    const all: MonthlyAttendanceRecord[] = JSON.parse(raw);
    return all.filter(r => r.year === year && r.month === month);
};

/**
 * PAYROLL BRIDGE
 * Converts MonthlyAttendanceRecords into Standard AttendanceRecords
 * for the Payroll Engine.
 */
export const bridgeGridToAttendance = (
    gridRecords: MonthlyAttendanceRecord[],
    companyId: string,
    userName: string
): AttendanceRecord[] => {
    return gridRecords.map(r => {
        const status: AttendanceStatus = r.hoursWorked >= 8 ? 'approved' : 'pending';
        const riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' = r.hoursWorked >= 8 ? 'LOW' : 'MEDIUM';

        // Format date properly YYYY-MM-DD
        const dateStr = `${r.year}-${String(r.month).padStart(2, '0')}-${String(r.day).padStart(2, '0')}`;

        const history: ActionLog[] = [{
            userId: 'system',
            userName: 'Salery Grid Sync',
            userRole: 'SYSTEM' as any,
            action: 'Generated from Monthly Grid',
            timestamp: Date.now(),
            details: `Generated by ${userName}`
        }];

        return {
            id: `grid-${r.id || Math.random().toString(36).substr(2, 9)}`,
            employeeId: r.employeeId,
            date: dateStr,
            hoursWorked: r.hoursWorked,
            status,
            riskLevel,
            type: 'manual',
            history,
            gpsTimeline: [],
            lastActionAt: Date.now(),
            validated: r.hoursWorked >= 8,
            manualReason: r.hoursWorked < 8 ? `Heures saisies: ${r.hoursWorked}h` : undefined
        };
    });
};
